import type { Config } from 'tailwindcss'

/* Precision Workbench · Tailwind token mapping.
   Replace content paths after copying this file into a project. */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        canvas: 'var(--bg-primary)',
        surface: 'var(--bg-surface)',
        elevated: 'var(--bg-elevated)',
        subtle: 'var(--bg-secondary)',
        muted: 'var(--bg-muted)',
        ink: 'var(--text-primary)',
        'ink-secondary': 'var(--text-secondary)',
        'ink-tertiary': 'var(--text-tertiary)',
        'on-strong': 'var(--text-on-strong)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-active': 'var(--accent-active)',
        'accent-soft': 'var(--accent-soft)',
        'on-accent': 'var(--on-accent)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        separator: 'var(--separator)',
        ring: 'var(--focus-ring)',
        success: 'var(--success)',
        'success-soft': 'var(--success-soft)',
        warning: 'var(--warning)',
        'warning-soft': 'var(--warning-soft)',
        danger: 'var(--danger)',
        'danger-hover': 'var(--danger-hover)',
        'danger-soft': 'var(--danger-soft)',
        overlay: 'var(--overlay)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        xs: ['var(--font-size-xs)', { lineHeight: 'var(--line-height-normal)' }],
        sm: ['var(--font-size-sm)', { lineHeight: 'var(--line-height-normal)' }],
        base: ['var(--font-size-md)', { lineHeight: 'var(--line-height-normal)' }],
        lg: ['var(--font-size-lg)', { lineHeight: 'var(--line-height-tight)' }],
        xl: ['var(--font-size-xl)', { lineHeight: 'var(--line-height-tight)' }],
        '2xl': ['var(--font-size-2xl)', { lineHeight: 'var(--line-height-tight)' }],
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        'control-sm': 'var(--control-height-sm)',
        'control-md': 'var(--control-height-md)',
        'control-lg': 'var(--control-height-lg)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        control: 'var(--shadow-control)',
        popover: 'var(--shadow-popover)',
        dialog: 'var(--shadow-dialog)',
        drawer: 'var(--shadow-drawer)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        out: 'var(--ease-out)',
      },
      zIndex: {
        base: 'var(--z-base)',
        sticky: 'var(--z-sticky)',
        assistant: 'var(--z-assistant)',
        'assistant-overlay': 'var(--z-assistant-overlay)',
        dialog: 'var(--z-dialog)',
        'dialog-content': 'var(--z-dialog-content)',
        popover: 'var(--z-popover)',
      },
      screens: {
        compact: { max: '620px' },
        narrow: { max: '760px' },
        workbench: { max: '900px' },
        panel: { max: '1100px' },
      },
    },
  },
  plugins: [],
} satisfies Config
